spring.profiles.active=demo

# 실행시 테스트 관리자들을 추가
app.add-test-admins=true
# 실행시 테스트 상품들을 추가
app.add-test-items=true
# 실행시 테스트 고객들을 추가
app.add-test-customers=true

spring.datasource.url=jdbc:h2:mem:test
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# jwt secret key
spring.jwt.secret="길면 길수록 좋은 secret key 입니다. 아무 값이나 넣어주세요 (저희는 HS256 를 쓰기 때문에 32 byte 이상이어야 합니다)"
